services:
  db:
    image: postgres:16
    container_name: healthcare_pg
    environment:
      POSTGRES_USER: health
      POSTGRES_PASSWORD: health_pw_change_me
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./:/workspace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U health -d healthcare"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
